name: archiquestcore
main: brain.BrainSpigot
version: 0.0.1
api-version: 1.16
author: breadmakers
softdepend: [AureliumSkills, Authme, PlaceholderAPI, ProtocolLib, SimpleClans]
description: the basic plugin of archi.quest project
commands:
    archiquest:
        description: archiquest
        usage: archiquest.commanduse /<command>
    hub:
        description: Move to hub
        usage: archiquest.commanduse /<command>
    survival:
        description: Move to survival
        usage: archiquest.commanduse /<command>
    creative:
        description: Move to creative
        usage: archiquest.commanduse /<command>
    archicreative:
        description: Move to archicreative
        usage: archiquest.commanduse /<command>
    tp:
        description: Teleport to player
        usage: archiquest.commanduse /<command> <player>
        aliases: [teleport, call, tpa, tpallow, tpaccept, tpyes, tphere, s]
    back:
        description: Teleport to previous position
        usage: archiquest.commanduse /<command>
    enderchest:
        description: Open your backpack
        usage: archiquest.commanduse /<command>
        aliases: ['ec']
    fly:
        description: Display player info
        usage: archiquest.commanduse /<command>
    speed:
        description: Set fly/walk speed
        usage: archiquest.commanduse /<command> <1-9>
    seen:
        description: Display player info
        usage: archiquest.commanduse /<command> <player>
    time:
        description: Set world time
        usage: archiquest.commanduse /<command> <day|night>
    weather:
        description: Set world weather
        usage: archiquest.commanduse /<command> <sun|rain>
    ptime:
        description: Set world time
        usage: archiquest.commanduse /<command> <day|night|reset>
    pweather:
        description: Set world weather
        usage: archiquest.commanduse /<command> <sun|rain|reset>
    repair:
        description: Repair item in hand
        usage: archiquest.commanduse /<command>
    help:
        description: Help
        usage: archiquest.commanduse /<command>
    idea:
        description: Idea
        usage: archiquest.commanduse /<command>
    links:
        description: Links
        usage: archiquest.commanduse /<command>
    chat:
        description: Chat
        usage: archiquest.commanduse /<command> <delete|undo|translate> <id>
    rp:
        description: Roleplay chat
        usage: archiquest.commanduse /<command> <message>
        aliases: [me, n, c, ws, do, try]
    menu:
        description: Menu
        usage: archiquest.commanduse /<command>
        aliases: [m]
    settings:
        description: Settings
        usage: archiquest.commanduse /<command>
    bread:
        description: Bread
        usage: archiquest.commanduse /<command>
    spawn:
        description: Teleport to spawn
        usage: archiquest.commanduse /<command>
    top:
        description: Teleport to top
        usage: archiquest.commanduse /<command>
    hat:
        description: Hat
        usage: archiquest.commanduse /<command>
    bag:
        description: BackPack
        usage: archiquest.commanduse /<command>
        aliases: [backpack]
    workbench:
        description: Workbench
        usage: archiquest.commanduse /<command>
        aliases: [craft]
    commands:
        description: List of commands
        usage: archiquest.commanduse /<command>
    feed:
        description: Feed
        usage: archiquest.commanduse /<command>
    heal:
        description: Heal
        usage: archiquest.commanduse /<command>
    near:
        description: Near players
        usage: archiquest.commanduse /<command>
    doublejump:
        description: Double Jump
        usage: archiquest.commanduse /<command>
    jump:
        description: Jump to target block
        usage: archiquest.commanduse /<command>
    ext:
        description: Ext
        usage: archiquest.commanduse /<command>
    tptoggle:
        description: Automatically deny all tp requests
        usage: archiquest.commanduse /<command>
    discord:
        description: Discord
        usage: archiquest.commanduse /<command>
    launcher:
        description: Launcher
        usage: archiquest.commanduse /<command>
    rules:
        description: Rules
        usage: archiquest.commanduse /<command>
    warp:
        description: Warps
        usage: archiquest.commanduse /<command>
        aliases: [w]
    sitonhead:
        description: Sit on head
        usage: archiquest.commanduse /<command>
        aliases: [sitonhands]
    head:
        description: Get player''s head
        usage: archiquest.commanduse /<command>
        aliases: [skull]
    gamemode:
        description: Set gamemode
        usage: archiquest.commanduse /<command> <0|1|2|3>
        aliases: [gm]
    patreon:
        description: Patreon
        usage: archiquest.commanduse /<command>
    sudo:
        description: Sudo
        usage: archiquest.commanduse /<command>
    warps:
        description: Homes list
        usage: archiquest.commanduse /<command>
        aliases: [wlist]
    youtube:
        description: Youtube
        usage: archiquest.commanduse /<command>
        aliases: [yt]
    vote:
        description: Vote for server
        usage: archiquest.commanduse /<command>
        aliases: [votes]
    start:
        description: Start the game
        usage: archiquest.commanduse /<command>
    joinmessage:
        description: Set join message
        usage: archiquest.commanduse /<command>
        aliases: [jm]
    afk:
        description: Away from keyboard
        usage: archiquest.commanduse /<command>
    lang:
        description: Language
        usage: archiquest.commanduse /<command> <ua|en|by|...|ru|>
    msg:
        description: Away from keyboard
        usage: archiquest.commanduse /<command> <player> <message>
    vanish:
        description: Away from keyboard
        usage: archiquest.commanduse /<command>
    invsee:
        description: Away from keyboard
        usage: archiquest.commanduse /<command> <player>
    npccmd:
        description: Away from keyboard
        usage: archiquest.commanduse /<command> <name> <cmd>
    home:
        description: Home
        usage: archiquest.commanduse /<command>
    homes:
        description: Homes
        usage: archiquest.commanduse /<command>
    openworld:
        description: OpenWorld
        usage: archiquest.commanduse /<command>
    gradient:
        description: Show you gradients
        usage: Use /gradient
    sgradient:
        description: Show you a list of gradients
        usage: Use /sgradient