name: archiquestcore
main: com.BrainSpigot
version: 0.0.1
api-version: 1.18
author: breadmakers
description: the basic plugin of archi.quest project
commands:
    bread:
        description: Display player info
        usage: Use /<command> <player>
    tp:
        description: Teleport to player
        usage: Use /<command>
        aliases: ['teleport', 'call', 'tpa', 'tpdeny', 'tpallow', 'tpaccept', 'tpcancel', 'tpno', 'tpyes']
    enderchest:
        description: Open your backpack
        usage: Use /<command>
        aliases: ['backpack', 'ec']